
(function(){
'use strict';
const root=document.getElementById('pw-redesign-v3');
if(!root)return;
const assets={"brandmark":"assets/logo/brandmark.png","wordmark":"assets/logo/wordmark.png","video":"assets/video/hero-v3.mp4","hero":"assets/v3/hero-poster.webp","signature":"assets/v3/signature.webp","detailMain":"assets/v3/detailMain.webp","detailBright":"assets/v3/detailBright.webp","detailHatch":"assets/v3/detailHatch.webp","detailInterior":"assets/v3/detailInterior.webp","detailSeats":"assets/v3/detailSeats.webp","detailTop":"assets/v3/detailTop.webp","detailTower":"assets/v3/detailTower.webp","wax":"assets/v3/wax.webp","compound":"assets/v3/compound.webp","ceramic":"assets/v3/ceramic.webp","plans":"assets/v3/plans.webp","memberSilver":"assets/v3/memberSilver.webp","memberGold":"assets/v3/memberGold.webp","memberPlatinum":"assets/v3/memberPlatinum.webp","dashboard":"assets/v3/dashboard.webp","covers":"assets/v3/covers.webp","gallery1":"assets/v3/gallery1.webp","gallery2":"assets/v3/gallery2.webp","gallery3":"assets/v3/gallery3.webp","gallery4":"assets/v3/gallery4.webp","blog1":"assets/v3/blog1.webp","blog2":"assets/v3/blog2.webp","blog3":"assets/v3/blog3.webp"};
root.querySelectorAll('[data-pw-img]').forEach(img=>{img.src=assets[img.dataset.pwImg];img.decoding='async';if(!img.closest('.pw-v2hero')&&!img.closest('.pw-logo'))img.loading='lazy';});
const byId=id=>root.querySelector('#'+id);
const video=byId('pw-hero-video');video.muted=true;video.defaultMuted=true;video.poster=assets.hero;video.src=assets.video;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let moving=!reduced;
function syncVideo(){const toggle=byId('pw-video-toggle');toggle.setAttribute('aria-pressed',String(moving));toggle.textContent=moving?'Ⅱ Pause video':'▶ Play video';if(moving){const play=video.play();if(play)play.catch(()=>{toggle.textContent='▶ Play video';toggle.setAttribute('aria-pressed','false');});}else{video.pause();}}
function setMotion(){root.classList.toggle('pw-still',!moving);byId('pw-motion').setAttribute('aria-pressed',String(moving));byId('pw-motion').innerHTML='<span>◉</span> Motion '+(moving?'on':'off');syncVideo();}
setMotion();
byId('pw-video-toggle').addEventListener('click',()=>{moving=video.paused;setMotion();});
byId('pw-motion').addEventListener('click',()=>{moving=!moving;setMotion();});
function goTo(id){const target=byId(id);if(target)target.scrollIntoView({behavior:moving&&!reduced?'smooth':'auto',block:'start'});}
root.querySelectorAll('a[href^="#pw-"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();goTo(a.getAttribute('href').slice(1));byId('pw-mobilemenu').hidden=true;byId('pw-menu').setAttribute('aria-expanded','false');byId('pw-menu').textContent='Menu +';}));
byId('pw-menu').addEventListener('click',()=>{const menu=byId('pw-mobilemenu');menu.hidden=!menu.hidden;byId('pw-menu').setAttribute('aria-expanded',String(!menu.hidden));byId('pw-menu').textContent=menu.hidden?'Menu +':'Close −';});
function animate(el){if(!moving||reduced||!el.animate)return;el.animate([{opacity:.25,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,easing:'ease-out'});}
root.querySelectorAll('[data-service]').forEach(btn=>btn.addEventListener('click',()=>{const alreadyOpen=btn.getAttribute('aria-expanded')==='true';root.querySelectorAll('[data-service]').forEach(b=>{const on=b===btn&&!alreadyOpen;b.setAttribute('aria-expanded',String(on));b.querySelector('.pw-plus').textContent=on?'−':'+';byId(b.getAttribute('aria-controls')).hidden=!on;});if(!alreadyOpen){const panel=byId(btn.getAttribute('aria-controls'));animate(panel);panel.scrollIntoView({behavior:moving&&!reduced?'smooth':'auto',block:'nearest'});}}));
const extras={'Teak care':'Teak cleaning and restoration matched to its condition. Custom quote.','Interior deep cleaning':'Focused care for compartments, cabin surfaces and interiors. Custom quote.','Hull cleaning coordination':'We coordinate in-water hull cleaning and confirm the scope for your boat and location. Custom quote.','Trip Ready prep':'Pre-departure preparation before you arrive. Two preps per month are included with Platinum.','Freshwater Rinse':'A focused pre- or post-trip rinse: glass and stainless wiped, covers reset and trash removed. Custom quote.'};
root.querySelectorAll('[data-extra]').forEach(btn=>btn.addEventListener('click',()=>{byId('pw-extra-description').textContent=extras[btn.dataset.extra];animate(byId('pw-extra-description'));}));
const plans={
 Silver:{label:'Silver / Essential care',head:'Keep the salt off.\nKeep the boat ready.',description:'For a boat that gets used and needs consistent cleaning between trips. We put your washes on a schedule and document every visit.',features:['Recurring maintenance washes on the schedule you choose: weekly, bi-weekly or monthly.','A full exterior wash and salt rinse every visit.','Removes light staining and helps prevent it from returning with consistent care.','Photos in your Slip after every visit, so you can see the work.','Standard scheduling, with your boat in our regular rotation.'],action:'Request a Silver plan',imageHead:'Clean boat.\nClear calendar.',perkLabel:'Simple, consistent care',perk:'We handle the regular washing. You get a clean boat and a record of every visit in your Slip.',cadence:'Weekly / bi-weekly / monthly',priority:'Standard scheduling'},
 Gold:{label:'Gold / Complete maintenance',head:'Beyond clean.\nProperly maintained.',description:'For owners who want regular washing and deeper monthly care. Your assigned detailer learns the boat and keeps a profile that grows with every visit.',features:['Recurring maintenance washes on a cadence built around how you use the boat.','A full exterior wash and salt rinse every visit.','A Full Detail every month: brightwork, rust and mild stain removal, hatch lips, compartments and interior cleaning.','Consistent cleaning helps prevent light and mild staining and discourages spiders and ants by clearing webs, residue and hiding spots.','Priority scheduling ahead of standard washes.','Your own assigned detailer who learns the boat.','A boat profile that builds visit over visit.','Photos in your Slip after every visit.'],action:'Request a Gold plan',imageHead:'Clean is good.\nMaintained is better.',perkLabel:'A Full Detail, every month',perk:'The deeper clean is part of the plan: brightwork, rust and stain removal, hatches, compartments and interior care.',cadence:'Custom cadence',priority:'Priority scheduling'},
 Platinum:{label:'Platinum / By invitation',head:'Your next run.\nAlready handled.',description:'For owners who want the details managed between trips. We learn your boat, keep it maintained, and get it ready before you arrive.',features:['Recurring maintenance washes on a cadence built around your boat.','A full exterior wash and salt rinse every visit.','A complete Full Detail every month.','Gold-level stain care and cleaning-based spider and ant prevention.','Two Trip Ready preps each month, included.','A consistent detailer who learns your boat and your Slip.','Service requests acknowledged within 24 hours between scheduled visits.','See a Spot? Send it to us. Reporting is always free; larger work is quoted before we do it.','Photos in your Slip after every visit.','Top scheduling priority and first access to new services.'],action:'Request an invite',imageHead:'Show up.\nHead out.',perkLabel:'Trip Ready / Twice a month, included',perk:'We wipe down the boat, remove canvas, ice the coolers, stock water and drinks, turn on electronics and stow the lines.',cadence:'Built around your boat',priority:'Our highest priority'}
};
function multiline(id,value){const el=byId(id);el.replaceChildren();value.split('\n').forEach((line,i)=>{if(i)el.appendChild(document.createElement('br'));el.appendChild(document.createTextNode(line));});}
function selectPlan(name,withMotion=true){
 root.querySelectorAll('[data-plan]').forEach(btn=>{const active=btn.dataset.plan===name;btn.setAttribute('aria-pressed',String(active));const action=btn.querySelector('.pw-metalaction');action.firstChild.textContent=(active?'Viewing ':'Explore ')+btn.dataset.plan+' ';});
 const plan=plans[name];byId('pw-plan-label').textContent=plan.label;multiline('pw-plan-head',plan.head);byId('pw-plan-description').textContent=plan.description;
 const list=byId('pw-plan-features');list.replaceChildren();plan.features.forEach(s=>{const li=document.createElement('li');li.textContent=s;list.appendChild(li);});
 byId('pw-plan-action').textContent=plan.action;byId('pw-plan-quote').dataset.member=name;byId('pw-plan-image-label').textContent=name+' membership';multiline('pw-plan-image-head',plan.imageHead);byId('pw-plan-perk-label').textContent=plan.perkLabel;byId('pw-plan-perk').textContent=plan.perk;byId('pw-plan-cadence').textContent=plan.cadence;byId('pw-plan-priority').textContent=plan.priority;root.querySelector('.pw-planimage img').src=assets[{Silver:'memberSilver',Gold:'memberGold',Platinum:'memberPlatinum'}[name]];
 if(withMotion)animate(byId('pw-planpanel'));
}
root.querySelectorAll('[data-plan]').forEach(btn=>btn.addEventListener('click',()=>selectPlan(btn.dataset.plan)));
selectPlan('Platinum',false);
byId('pw-dashboard-expand').addEventListener('click',()=>{const expanded=byId('pw-portal').classList.toggle('pw-expanded');byId('pw-dashboard-expand').setAttribute('aria-expanded',String(expanded));byId('pw-dashboard-expand').firstChild.textContent=expanded?'Return to overview ':'Take a closer look ';});

const gallery={gallery1:['Hull gloss','Deep reflection along the waterfront'],gallery2:['Trailer ready','Full exterior care before the next launch'],gallery3:['Stern detail','Brightwork, transom and engines brought back into focus'],gallery4:['Dockside ready','Clean from bow to stern and ready at the lift']};
root.querySelectorAll('[data-gallery]').forEach(btn=>btn.addEventListener('click',()=>{root.querySelectorAll('[data-gallery]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const key=btn.dataset.gallery;byId('pw-gallery-feature').src=assets[key];byId('pw-gallery-feature').alt=gallery[key][0]+' from the Propwash work gallery';byId('pw-gallery-name').textContent=gallery[key][0];byId('pw-gallery-detail').textContent=gallery[key][1];animate(byId('pw-gallery-feature'));}));
const form=byId('pw-quote-form'),boat=byId('pw-form-boat'),contact=byId('pw-form-contact'),done=byId('pw-form-done');
function step(n){boat.hidden=n!==1;contact.hidden=n!==2;done.hidden=n!==3;byId('pw-form-note').hidden=n===3;boat.querySelectorAll('input,select').forEach(el=>el.disabled=n!==1);contact.querySelectorAll('input,select,textarea').forEach(el=>el.disabled=n!==2);byId('pw-form-stage').textContent=n===1?'01 / Your boat':n===2?'02 / Your details':'Preview / Complete';byId('pw-form-count').textContent=n===3?'Nothing sent':'Step '+n+' of 2';}
byId('pw-next').addEventListener('click',()=>{const valid=[...boat.querySelectorAll('input,select')].every(el=>el.reportValidity());if(valid){step(2);animate(contact);byId('pw-firstname').focus({preventScroll:true});}});
byId('pw-back').addEventListener('click',()=>step(1));
form.addEventListener('submit',e=>{if(contact.hidden){e.preventDefault();byId('pw-next').click();return;}const valid=[...contact.querySelectorAll('input,select,textarea')].every(el=>el.reportValidity());if(!valid){e.preventDefault();return;}boat.querySelectorAll('input,select').forEach(el=>el.disabled=false);const send=byId('pw-preview-request');send.disabled=true;send.firstChild.textContent='Sending ';});
byId('pw-restart').addEventListener('click',()=>{form.reset();step(1);});
root.querySelectorAll('[data-quote]').forEach(btn=>btn.addEventListener('click',()=>{step(1);byId('pw-interest').value=btn.dataset.quote;goTo('pw-quote');}));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){animate(entry.target);observer.unobserve(entry.target);}});},{threshold:.15});root.querySelectorAll('.pw-sectionhead,.pw-resultintro,.pw-portalcopy,.pw-moments').forEach(el=>observer.observe(el));}

function showDetailOverview(){root.querySelectorAll('[data-detail]').forEach(b=>b.setAttribute('aria-pressed','false'));byId('pw-detail-feature').src=assets.detailMain;byId('pw-detail-feature').alt='Propwash Full Detail in progress';byId('pw-detail-count').textContent='01 / 07';byId('pw-detail-title').textContent='The complete reset.';byId('pw-detail-caption').textContent='A Full Detail reaches beyond the obvious surfaces. Click this large image any time to return here.';animate(byId('pw-detail-feature'));}
byId('pw-detail-reset').addEventListener('click',showDetailOverview);
root.querySelectorAll('[data-detail]').forEach((button,index)=>button.addEventListener('click',()=>{root.querySelectorAll('[data-detail]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));byId('pw-detail-feature').src=assets[button.dataset.detail];byId('pw-detail-feature').alt=button.querySelector('img').alt;byId('pw-detail-count').textContent=String(index+2).padStart(2,'0')+' / 07';byId('pw-detail-title').textContent=button.dataset.title;byId('pw-detail-caption').textContent=button.dataset.caption;animate(byId('pw-detail-feature'));}));
const home=byId('pw-home-view'),memberPage=byId('pw-membership-page');
function showMemberPage(){const plan=byId('pw-plan-quote').dataset.member||'Platinum';memberPage.classList.remove('pw-member-silver','pw-member-gold','pw-member-platinum');memberPage.classList.add('pw-member-'+plan.toLowerCase());byId('pw-member-tiernote').textContent={Silver:'01 / Essential care',Gold:'02 / Complete maintenance',Platinum:'03 / By invitation'}[plan];byId('pw-member-selected').textContent=plan;byId('pw-member-summary').textContent={Silver:'Recurring washes that remove light staining and help prevent it from returning, on the schedule you choose.',Gold:'Recurring washes and a monthly Full Detail for mild staining, deeper care and a boat that stays less inviting to pests.',Platinum:'Complete monthly care, two Trip Ready preps and a response to service requests within 24 hours.'}[plan];byId('pw-member-done-title').textContent='Your '+plan+' inquiry is ready.';home.hidden=true;memberPage.hidden=false;memberStep(1);memberPage.scrollIntoView({behavior:'auto',block:'start'});}
function closeMemberPage(){memberPage.hidden=true;home.hidden=false;byId('pw-membership').scrollIntoView({behavior:'auto',block:'start'});}
byId('pw-plan-quote').addEventListener('click',showMemberPage);byId('pw-member-back').addEventListener('click',closeMemberPage);byId('pw-member-close').addEventListener('click',closeMemberPage);
function memberStep(n){byId('pw-member-step1').hidden=n!==1;byId('pw-member-step2').hidden=n!==2;byId('pw-member-done').hidden=n!==3;byId('pw-member-step1').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=n!==1);byId('pw-member-step2').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=n!==2);byId('pw-member-stage').textContent=n===1?'01 / The boat':n===2?'02 / Your details':'Inquiry preview';byId('pw-member-count').textContent=n===3?'Nothing sent':'Step '+n+' of 2';}
byId('pw-member-next').addEventListener('click',()=>{if([...byId('pw-member-step1').querySelectorAll('input,select,textarea')].every(el=>el.reportValidity()))memberStep(2);});byId('pw-member-prev').addEventListener('click',()=>memberStep(1));byId('pw-member-restart').addEventListener('click',()=>memberStep(1));byId('pw-member-form').addEventListener('submit',e=>{if(!byId('pw-member-step1').hidden){e.preventDefault();byId('pw-member-next').click();return;}const valid=[...byId('pw-member-step2').querySelectorAll('input,select,textarea')].every(el=>el.reportValidity());if(!valid){e.preventDefault();return;}byId('pw-member-plan').value=byId('pw-member-selected').textContent;byId('pw-member-step1').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=false);const send=byId('pw-member-preview');send.disabled=true;send.firstChild.textContent='Sending ';});
const designState={header:'balanced',detailLayout:'filmstrip'};function renderOptions(){root.classList.toggle('pw-header-compact',designState.header==='compact');root.classList.toggle('pw-detail-grid',designState.detailLayout==='grid');}renderOptions();if(globalThis.Tweak){const heroTweak=new Tweak({container:root.querySelector('.pw-v2hero'),onChange:renderOptions});heroTweak.addSelect(designState,'header',{label:'Header spacing',options:[{label:'Balanced',value:'balanced'},{label:'Compact',value:'compact'}]});const detailTweak=new Tweak({container:byId('pw-results'),onChange:renderOptions});detailTweak.addSelect(designState,'detailLayout',{label:'Full Detail layout',options:[{label:'Filmstrip',value:'filmstrip'},{label:'Grid',value:'grid'}]});}

})();
